export const breadcrumbConfig: Record<string, { label: string }> = {
  "/dashboard": { label: "Kontrolna tabla" },
  "/buildings": { label: "Zgrade" },
  "/buildings/create": { label: "Dodavanje zgrade" },
  "/buildings/:id/edit": { label: "Izmena zgrade" },
  "/company/:companyId": { label: "Kompanija" },
  "/agency": { label: "Agencije" },
  "/agency/:id": { label: "Detalji agencije" },
  "/contracts": { label: "Ugovori" },
  "/requests": { label: "Zahtevi" },
  "/discount-requests": { label: "Zahtevi za popust" },
  "/apartments": { label: "Stanovi" },
  "/apartments/:apartmentId/buy": { label: "Kupvina stana" },
  "/reservations": { label: "Rezervacije" },
  "/profile/:id": { label: "Profil" },
  "/admin": { label: "Administratorska tabla" },
};
